name: Deploy
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Git pull, build app and restart pm2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
            cd cermat
            git pull
            cd client
            npm install
            npm run build
            cd ../server
            npm install
            npm run build
            cp .env build/
            pm2 restart maturoid